---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: monitoring
  labels:
    project: k8s-deployment-exporter
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMC4yLjIyNCI6eyJhdXRoIjoiZG1WdWRIVncienBDYVhOdGFXeHNZV2d4TkRBM0tnPT0ifX19
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-deployment-exporter
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-deployment-exporter
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-deployment-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-deployment-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-deployment-exporter
    namespace: monitoring

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment-exporter
  namespace: monitoring
  labels:
    app: k8s-deployment-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployment-exporter
  template:
    metadata:
      labels:
        app: k8s-deployment-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: k8s-deployment-exporter
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: exporter
          image: 10.10.2.224/venturo/k8s-deployment-exporter:latest
          imagePullPolicy: Always
          args:
            - --metrics-addr=:9101
            - --scrape-interval=15
            # - --namespace=default  # Uncomment to monitor specific namespace
          ports:
            - name: metrics
              containerPort: 9101
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment-exporter
  namespace: monitoring
  labels:
    app: k8s-deployment-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9101
      targetPort: metrics
      protocol: TCP
  selector:
    app: k8s-deployment-exporter

---
# ServiceMonitor for Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-deployment-exporter
  namespace: monitoring
  labels:
    app: k8s-deployment-exporter
spec:
  selector:
    matchLabels:
      app: k8s-deployment-exporter
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
