---
apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
  namespace: monitoring
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMC4yLjIyNCI6eyJhdXRoIjoiZG1WdWRIVnd6cENhWE50YVd4c1lXZ3hOREEzS2c9PSJ9fX0K